[package]
name = "obj-to-pathfinding-grid"
version = "0.1.0"
authors = ["vagola <vladislavs.golubs@yandex.ru>"]
edition = "2018"

[dependencies]
flying-pathfinding = { git = "https://github.com/negaisa/flying-pathfinding" }
structopt = "0.3"
nalgebra = "0.21.0"
obj = "0.10.0"